### ISSUE TITLE
Potential overwrite of resources with dynamodb and dynamodb2_name

### ISSUE THREAD

**Issue by cytopia** [Flaconi/terraform-aws-microservice#16]
Finding found by @ronny-panknin-flaconi :

## Description
Looking at the dynamodb.tf and dynamodb2.tf configuration, there seems to be an issue with name collision :

### 1/2 building locals
**dynamodb.tf**
```hcl
locals {
  dynamodb_name = length(var.dynamodb_name_override) > 0 ? var.dynamodb_name_override : var.name
}
```

**dynamodb2.tf**
```hcl
locals {
  dynamodb2_name = length(var.dynamodb2_name_override) > 0 ? var.dynamodb2_name_override : var.name
}
```

### 2/2 local name assignment

**dynamodb.tf**
```hcl
module "dynamodb" {
  ...
  namespace = ""
  stage     = ""
  name      = local.dynamodb_name
  ...
```

**dynamodb2.tf**
```hcl
module "dynamodb2" {
  ...
  namespace = ""
  stage     = ""
  name      = local.dynamodb2_name
```

## Issue

If neither `var.dynamodb_name_override` nor  `var.dynamodb2_name_override` are specified, which are **optional**, the one which gets rolled out later *would/could* overwrite the first one.

## How to resolve?

This is tricky and there are multiple solutions to it, the big question is how do we make it consistent and easily understandable? Current consistency is to use `var.name` as the single point of truth for resource names.

Only thing I could come up with is to make `dynamodb(2)?_name_override` required, which however (will be inconsistent with other services provided.

@maartenvanderhoef any thoughts on this one?

**Comment by cytopia** [comment]
We could probably also do the following for dynamodb2.tf

```diff
locals {
-  dynamodb2_name = length(var.dynamodb2_name_override) > 0 ? var.dynamodb2_name_override : var.name
+  dynamodb2_name = length(var.dynamodb2_name_override) > 0 ? var.dynamodb2_name_override : concat(var.name, "2")
}
```

This would allow us to keep both overwrites and be consistent with our inconsistency. WDYT?

**Comment by maartenvanderhoef** [comment]
That's perfect.
